name: StoneChallenge
configs:
  Develop: debug
  Production: release
packages:
  RAMRequestManager:
    url: git@github.com:thufik/RAMRequestManager.git
    branch: master
fileGroups:
  - StoneChallenge
  - StoneChallengeTests
  - StoneChallengeUITests
targets:
  RickAndMorty:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: StoneChallenge
    info:
      path: StoneChallenge/Resources/StoneChallenge-Info.plist
      properties:
        BaseURL: $(BaseURL)
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitLandscape]
        UIBackgroundModes: [fetch, remote-notification]
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersion: $(MARKETING_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication: [{UISceneConfigurationName: "Default Configuration", UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate"}]
        UIApplicationSupportsIndirectInputEvents: true
        UIUserInterfaceStyle: Light
        UILaunchStoryboardName: LaunchScreen
    configFiles:
      Develop: StoneChallenge/Resources/StoneChallenge-Develop.xcconfig
      Production: StoneChallenge/Resources/StoneChallenge-Release.xcconfig
    settings:
      base:
        PRODUCT_NAME: RickAndMorty
        PRODUCT_BUNDLE_IDENTIFIER: br.com.rick.morty.dev
        DEVELOPMENT_TEAM: 9THUCJMT4V
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Manual
        PROVISIONING_PROFILE_SPECIFIER: match Development br.com.valid.rgpi.dev
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: true
        ONLY_ACTIVE_ARCH: true
        INFOPLIST_FILE: StoneChallenge/Resources/StoneChallenge-Info.plist
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: RAMRequestManager
      
  StoneChallengeTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - StoneChallengeTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      SUPPORTS_MACCATALYST: false
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
      TARGETED_DEVICE_FAMILY: 1
      
